from __future__ import annotations

from typing import Protocol


class CityRepository(Protocol):
    def list_cities(self) -> list[dict]: ...

    def read_collection(self, city_id: str, suffix: str) -> list[dict]: ...

    def get_scene(self, city_id: str) -> dict[str, list[dict]]: ...

    def get_building(self, city_id: str, building_id: str) -> dict | None: ...

    def get_bridge(self, city_id: str, bridge_id: str) -> dict | None: ...

    def get_street(self, city_id: str, street_id: str) -> dict | None: ...

    def get_building_papers(
        self, city_id: str, building_id: str, floor_id: str | None = None, limit: int = 200, cursor: str | None = None
    ) -> list[dict]: ...

    def get_building_edges(
        self, city_id: str, building_id: str, floor_id: str | None = None, limit: int = 200, cursor: str | None = None
    ) -> list[dict]: ...

    def get_bridge_edges(self, city_id: str, bridge_id: str, limit: int = 200, cursor: str | None = None) -> list[dict]: ...
