"""platform schema

Revision ID: 20260917_0001
Revises: 
Create Date: 2026-09-17 13:59:02.833655
"""
from typing import Sequence, Union

from alembic import op
import pgvector.sqlalchemy.vector
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '20260917_0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('cities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=240), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('target_paper_count', sa.Integer(), nullable=False),
    sa.Column('paper_count', sa.Integer(), nullable=False),
    sa.Column('edge_count', sa.Integer(), nullable=False),
    sa.Column('building_count', sa.Integer(), nullable=False),
    sa.Column('district_count', sa.Integer(), nullable=False),
    sa.Column('algorithm_version', sa.String(length=120), nullable=False),
    sa.Column('embedding_model', sa.String(length=240), nullable=False),
    sa.Column('source_version', sa.String(length=120), nullable=False),
    sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('research', 'seeded')", name='ck_cities_kind'),
    sa.CheckConstraint("status IN ('draft', 'building', 'ready', 'failed', 'cancelled')", name='ck_cities_status'),
    sa.CheckConstraint('target_paper_count BETWEEN 10 AND 100000', name='ck_cities_target_paper_count'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_table('ingestion_cache',
    sa.Column('request_fingerprint', sa.String(length=128), nullable=False),
    sa.Column('response', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('etag', sa.Text(), nullable=True),
    sa.Column('source_status', sa.Integer(), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('request_fingerprint')
    )
    op.create_table('papers',
    sa.Column('openalex_id', sa.Text(), nullable=False),
    sa.Column('doi', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=False),
    sa.Column('publication_year', sa.SmallInteger(), nullable=True),
    sa.Column('venue', sa.Text(), nullable=False),
    sa.Column('publisher', sa.Text(), nullable=False),
    sa.Column('citation_count', sa.Integer(), nullable=False),
    sa.Column('open_access', sa.Boolean(), nullable=False),
    sa.Column('code_available', sa.Boolean(), nullable=False),
    sa.Column('data_available', sa.Boolean(), nullable=False),
    sa.Column('authors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('author_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('institutions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('institution_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('topics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('methods', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('datasets', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('openalex_id')
    )
    op.create_index('ix_papers_search_vector', 'papers', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index('uq_papers_normalized_doi', 'papers', [sa.literal_column('lower(doi)')], unique=True, postgresql_where=sa.text('doi IS NOT NULL'))
    op.create_table('assistant_conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('city_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('build_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('city_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('stage', sa.String(length=60), nullable=False),
    sa.Column('progress_current', sa.Integer(), nullable=False),
    sa.Column('progress_total', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('attempts', sa.SmallInteger(), nullable=False),
    sa.Column('locked_by', sa.String(length=240), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("status IN ('queued', 'running', 'succeeded', 'failed', 'cancelled')", name='ck_build_jobs_status'),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_build_jobs_claim', 'build_jobs', ['status', 'created_at'], unique=False)
    op.create_table('city_seeds',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('city_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.SmallInteger(), nullable=False),
    sa.Column('raw_input', sa.Text(), nullable=False),
    sa.Column('resolved_openalex_id', sa.Text(), nullable=True),
    sa.Column('match_type', sa.String(length=40), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('resolution_status', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('city_id', 'position', name='uq_city_seeds_position')
    )
    op.create_table('city_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('city_id', sa.UUID(), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('counts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('aggregates', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('city_id', 'year', name='uq_city_snapshots_year')
    )
    op.create_table('community_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('city_id', sa.UUID(), nullable=False),
    sa.Column('algorithm', sa.String(length=80), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('random_seed', sa.Integer(), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('districts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('city_id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(length=120), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('semantic_domain', sa.String(length=120), nullable=False),
    sa.Column('semantic_domain_name', sa.Text(), nullable=False),
    sa.Column('color', sa.String(length=16), nullable=False),
    sa.Column('labels', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(), nullable=True),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('z', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('city_id', 'external_id', name='uq_districts_external_id')
    )
    op.create_table('paper_edges',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('city_id', sa.UUID(), nullable=False),
    sa.Column('source_openalex_id', sa.Text(), nullable=False),
    sa.Column('target_openalex_id', sa.Text(), nullable=False),
    sa.Column('edge_type', sa.String(length=60), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('components', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('directed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('city_id', 'source_openalex_id', 'target_openalex_id', 'edge_type', name='uq_paper_edges_pair_type')
    )
    op.create_index('ix_paper_edges_source', 'paper_edges', ['city_id', 'source_openalex_id'], unique=False)
    op.create_index('ix_paper_edges_target', 'paper_edges', ['city_id', 'target_openalex_id'], unique=False)
    op.create_table('paper_embeddings',
    sa.Column('openalex_id', sa.Text(), nullable=False),
    sa.Column('model', sa.String(length=240), nullable=False),
    sa.Column('dimensions', sa.SmallInteger(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['openalex_id'], ['papers.openalex_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('openalex_id', 'model')
    )
    op.create_table('paper_references',
    sa.Column('source_openalex_id', sa.Text(), nullable=False),
    sa.Column('target_openalex_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['source_openalex_id'], ['papers.openalex_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('source_openalex_id', 'target_openalex_id')
    )
    op.create_table('assistant_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('structured_content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model', sa.String(length=240), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['assistant_conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('buildings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('city_id', sa.UUID(), nullable=False),
    sa.Column('district_id', sa.UUID(), nullable=True),
    sa.Column('external_id', sa.String(length=120), nullable=False),
    sa.Column('node_count', sa.Integer(), nullable=False),
    sa.Column('edge_count', sa.Integer(), nullable=False),
    sa.Column('internal_density', sa.Float(), nullable=False),
    sa.Column('avg_core', sa.Float(), nullable=False),
    sa.Column('max_core', sa.Integer(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('footprint', sa.Float(), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('z', sa.Float(), nullable=False),
    sa.Column('top_labels', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('semantic_domain', sa.String(length=120), nullable=False),
    sa.Column('semantic_domain_name', sa.Text(), nullable=False),
    sa.Column('semantic_color', sa.String(length=16), nullable=False),
    sa.Column('profile', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('original_labels', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('activation', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('activation_score', sa.Float(), nullable=False),
    sa.Column('quality_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('city_id', 'external_id', name='uq_buildings_external_id')
    )
    op.create_table('answer_citations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=30), nullable=False),
    sa.Column('entity_id', sa.Text(), nullable=False),
    sa.Column('claim_index', sa.Integer(), nullable=False),
    sa.Column('support_score', sa.Float(), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['assistant_messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('building_relationships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('city_id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(length=160), nullable=False),
    sa.Column('source_building_id', sa.UUID(), nullable=False),
    sa.Column('target_building_id', sa.UUID(), nullable=False),
    sa.Column('relationship_kind', sa.String(length=30), nullable=False),
    sa.Column('relationship_type', sa.String(length=80), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('distance', sa.Float(), nullable=False),
    sa.Column('components', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('activation_score', sa.Float(), nullable=False),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_building_id'], ['buildings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_building_id'], ['buildings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('city_id', 'external_id', name='uq_relationships_external_id')
    )
    op.create_table('floors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('city_id', sa.UUID(), nullable=False),
    sa.Column('building_id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(length=140), nullable=False),
    sa.Column('floor_index', sa.SmallInteger(), nullable=False),
    sa.Column('core_min', sa.Integer(), nullable=False),
    sa.Column('core_max', sa.Integer(), nullable=False),
    sa.Column('node_count', sa.Integer(), nullable=False),
    sa.Column('top_labels', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('activation_score', sa.Float(), nullable=False),
    sa.Column('year_min', sa.SmallInteger(), nullable=True),
    sa.Column('year_max', sa.SmallInteger(), nullable=True),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('building_id', 'floor_index', name='uq_floors_building_index')
    )
    op.create_table('city_papers',
    sa.Column('city_id', sa.UUID(), nullable=False),
    sa.Column('openalex_id', sa.Text(), nullable=False),
    sa.Column('external_paper_id', sa.String(length=120), nullable=False),
    sa.Column('is_seed', sa.Boolean(), nullable=False),
    sa.Column('seed_position', sa.SmallInteger(), nullable=True),
    sa.Column('seed_relevance', sa.Float(), nullable=False),
    sa.Column('expansion_depth', sa.SmallInteger(), nullable=False),
    sa.Column('expansion_source', sa.String(length=80), nullable=False),
    sa.Column('building_id', sa.UUID(), nullable=True),
    sa.Column('floor_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['floor_id'], ['floors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['openalex_id'], ['papers.openalex_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('city_id', 'openalex_id'),
    sa.UniqueConstraint('city_id', 'external_paper_id', name='uq_city_papers_external_id')
    )
    op.create_index('ix_city_papers_building', 'city_papers', ['city_id', 'building_id'], unique=False)
    op.create_index('ix_city_papers_external_id', 'city_papers', ['city_id', 'external_paper_id'], unique=False)
    op.create_index('ix_city_papers_seed_relevance', 'city_papers', ['city_id', sa.literal_column('seed_relevance DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_city_papers_seed_relevance', table_name='city_papers')
    op.drop_index('ix_city_papers_external_id', table_name='city_papers')
    op.drop_index('ix_city_papers_building', table_name='city_papers')
    op.drop_table('city_papers')
    op.drop_table('floors')
    op.drop_table('building_relationships')
    op.drop_table('answer_citations')
    op.drop_table('buildings')
    op.drop_table('assistant_messages')
    op.drop_table('paper_references')
    op.drop_table('paper_embeddings')
    op.drop_index('ix_paper_edges_target', table_name='paper_edges')
    op.drop_index('ix_paper_edges_source', table_name='paper_edges')
    op.drop_table('paper_edges')
    op.drop_table('districts')
    op.drop_table('community_runs')
    op.drop_table('city_snapshots')
    op.drop_table('city_seeds')
    op.drop_index('ix_build_jobs_claim', table_name='build_jobs')
    op.drop_table('build_jobs')
    op.drop_table('assistant_conversations')
    op.drop_index('uq_papers_normalized_doi', table_name='papers', postgresql_where=sa.text('doi IS NOT NULL'))
    op.drop_index('ix_papers_search_vector', table_name='papers', postgresql_using='gin')
    op.drop_table('papers')
    op.drop_table('ingestion_cache')
    op.drop_table('cities')
    # ### end Alembic commands ###
